import os

PRICE_TTL_HOURS = float(os.getenv("PRICE_TTL_HOURS", "0.5"))
INDICATOR_TTL_HOURS = 0.5
FORECAST_TTL_HOURS = 1
NEWS_TTL_HOURS = 1
COMPANY_TTL_HOURS = 4
RATIO_TTL_HOURS = 2
SECTOR_TTL_HOURS = 2
PORTFOLIO_TTL_HOURS = 0.25
